version: '3.7'
services:
  postgresql_db:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql_db/data
      - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
