// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package grpc;

public interface FindProductsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FindProducts)
    com.google.protobuf.MessageOrBuilder {
}
