// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package grpc;

/**
 * Protobuf type {@code ProductList}
 */
public  final class ProductList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ProductList)
    ProductListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProductList.newBuilder() to construct.
  private ProductList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductList() {
    listProducts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProductList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProductList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              listProducts_ = new java.util.ArrayList<grpc.ProductList>();
              mutable_bitField0_ |= 0x00000001;
            }
            listProducts_.add(
                input.readMessage(grpc.ProductList.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        listProducts_ = java.util.Collections.unmodifiableList(listProducts_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.ProductProto.internal_static_ProductList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.ProductProto.internal_static_ProductList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.ProductList.class, grpc.ProductList.Builder.class);
  }

  public static final int LISTPRODUCTS_FIELD_NUMBER = 1;
  private java.util.List<grpc.ProductList> listProducts_;
  /**
   * <code>repeated .ProductList listProducts = 1;</code>
   */
  public java.util.List<grpc.ProductList> getListProductsList() {
    return listProducts_;
  }
  /**
   * <code>repeated .ProductList listProducts = 1;</code>
   */
  public java.util.List<? extends grpc.ProductListOrBuilder> 
      getListProductsOrBuilderList() {
    return listProducts_;
  }
  /**
   * <code>repeated .ProductList listProducts = 1;</code>
   */
  public int getListProductsCount() {
    return listProducts_.size();
  }
  /**
   * <code>repeated .ProductList listProducts = 1;</code>
   */
  public grpc.ProductList getListProducts(int index) {
    return listProducts_.get(index);
  }
  /**
   * <code>repeated .ProductList listProducts = 1;</code>
   */
  public grpc.ProductListOrBuilder getListProductsOrBuilder(
      int index) {
    return listProducts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < listProducts_.size(); i++) {
      output.writeMessage(1, listProducts_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < listProducts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, listProducts_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.ProductList)) {
      return super.equals(obj);
    }
    grpc.ProductList other = (grpc.ProductList) obj;

    if (!getListProductsList()
        .equals(other.getListProductsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getListProductsCount() > 0) {
      hash = (37 * hash) + LISTPRODUCTS_FIELD_NUMBER;
      hash = (53 * hash) + getListProductsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.ProductList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ProductList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ProductList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ProductList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ProductList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ProductList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ProductList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.ProductList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.ProductList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.ProductList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.ProductList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.ProductList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.ProductList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ProductList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ProductList)
      grpc.ProductListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.ProductProto.internal_static_ProductList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.ProductProto.internal_static_ProductList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.ProductList.class, grpc.ProductList.Builder.class);
    }

    // Construct using grpc.ProductList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getListProductsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (listProductsBuilder_ == null) {
        listProducts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        listProductsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.ProductProto.internal_static_ProductList_descriptor;
    }

    @java.lang.Override
    public grpc.ProductList getDefaultInstanceForType() {
      return grpc.ProductList.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.ProductList build() {
      grpc.ProductList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.ProductList buildPartial() {
      grpc.ProductList result = new grpc.ProductList(this);
      int from_bitField0_ = bitField0_;
      if (listProductsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          listProducts_ = java.util.Collections.unmodifiableList(listProducts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.listProducts_ = listProducts_;
      } else {
        result.listProducts_ = listProductsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.ProductList) {
        return mergeFrom((grpc.ProductList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.ProductList other) {
      if (other == grpc.ProductList.getDefaultInstance()) return this;
      if (listProductsBuilder_ == null) {
        if (!other.listProducts_.isEmpty()) {
          if (listProducts_.isEmpty()) {
            listProducts_ = other.listProducts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureListProductsIsMutable();
            listProducts_.addAll(other.listProducts_);
          }
          onChanged();
        }
      } else {
        if (!other.listProducts_.isEmpty()) {
          if (listProductsBuilder_.isEmpty()) {
            listProductsBuilder_.dispose();
            listProductsBuilder_ = null;
            listProducts_ = other.listProducts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            listProductsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getListProductsFieldBuilder() : null;
          } else {
            listProductsBuilder_.addAllMessages(other.listProducts_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.ProductList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.ProductList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<grpc.ProductList> listProducts_ =
      java.util.Collections.emptyList();
    private void ensureListProductsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        listProducts_ = new java.util.ArrayList<grpc.ProductList>(listProducts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.ProductList, grpc.ProductList.Builder, grpc.ProductListOrBuilder> listProductsBuilder_;

    /**
     * <code>repeated .ProductList listProducts = 1;</code>
     */
    public java.util.List<grpc.ProductList> getListProductsList() {
      if (listProductsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(listProducts_);
      } else {
        return listProductsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ProductList listProducts = 1;</code>
     */
    public int getListProductsCount() {
      if (listProductsBuilder_ == null) {
        return listProducts_.size();
      } else {
        return listProductsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ProductList listProducts = 1;</code>
     */
    public grpc.ProductList getListProducts(int index) {
      if (listProductsBuilder_ == null) {
        return listProducts_.get(index);
      } else {
        return listProductsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ProductList listProducts = 1;</code>
     */
    public Builder setListProducts(
        int index, grpc.ProductList value) {
      if (listProductsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListProductsIsMutable();
        listProducts_.set(index, value);
        onChanged();
      } else {
        listProductsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ProductList listProducts = 1;</code>
     */
    public Builder setListProducts(
        int index, grpc.ProductList.Builder builderForValue) {
      if (listProductsBuilder_ == null) {
        ensureListProductsIsMutable();
        listProducts_.set(index, builderForValue.build());
        onChanged();
      } else {
        listProductsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ProductList listProducts = 1;</code>
     */
    public Builder addListProducts(grpc.ProductList value) {
      if (listProductsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListProductsIsMutable();
        listProducts_.add(value);
        onChanged();
      } else {
        listProductsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ProductList listProducts = 1;</code>
     */
    public Builder addListProducts(
        int index, grpc.ProductList value) {
      if (listProductsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListProductsIsMutable();
        listProducts_.add(index, value);
        onChanged();
      } else {
        listProductsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ProductList listProducts = 1;</code>
     */
    public Builder addListProducts(
        grpc.ProductList.Builder builderForValue) {
      if (listProductsBuilder_ == null) {
        ensureListProductsIsMutable();
        listProducts_.add(builderForValue.build());
        onChanged();
      } else {
        listProductsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ProductList listProducts = 1;</code>
     */
    public Builder addListProducts(
        int index, grpc.ProductList.Builder builderForValue) {
      if (listProductsBuilder_ == null) {
        ensureListProductsIsMutable();
        listProducts_.add(index, builderForValue.build());
        onChanged();
      } else {
        listProductsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ProductList listProducts = 1;</code>
     */
    public Builder addAllListProducts(
        java.lang.Iterable<? extends grpc.ProductList> values) {
      if (listProductsBuilder_ == null) {
        ensureListProductsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, listProducts_);
        onChanged();
      } else {
        listProductsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ProductList listProducts = 1;</code>
     */
    public Builder clearListProducts() {
      if (listProductsBuilder_ == null) {
        listProducts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        listProductsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ProductList listProducts = 1;</code>
     */
    public Builder removeListProducts(int index) {
      if (listProductsBuilder_ == null) {
        ensureListProductsIsMutable();
        listProducts_.remove(index);
        onChanged();
      } else {
        listProductsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ProductList listProducts = 1;</code>
     */
    public grpc.ProductList.Builder getListProductsBuilder(
        int index) {
      return getListProductsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ProductList listProducts = 1;</code>
     */
    public grpc.ProductListOrBuilder getListProductsOrBuilder(
        int index) {
      if (listProductsBuilder_ == null) {
        return listProducts_.get(index);  } else {
        return listProductsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ProductList listProducts = 1;</code>
     */
    public java.util.List<? extends grpc.ProductListOrBuilder> 
         getListProductsOrBuilderList() {
      if (listProductsBuilder_ != null) {
        return listProductsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(listProducts_);
      }
    }
    /**
     * <code>repeated .ProductList listProducts = 1;</code>
     */
    public grpc.ProductList.Builder addListProductsBuilder() {
      return getListProductsFieldBuilder().addBuilder(
          grpc.ProductList.getDefaultInstance());
    }
    /**
     * <code>repeated .ProductList listProducts = 1;</code>
     */
    public grpc.ProductList.Builder addListProductsBuilder(
        int index) {
      return getListProductsFieldBuilder().addBuilder(
          index, grpc.ProductList.getDefaultInstance());
    }
    /**
     * <code>repeated .ProductList listProducts = 1;</code>
     */
    public java.util.List<grpc.ProductList.Builder> 
         getListProductsBuilderList() {
      return getListProductsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.ProductList, grpc.ProductList.Builder, grpc.ProductListOrBuilder> 
        getListProductsFieldBuilder() {
      if (listProductsBuilder_ == null) {
        listProductsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.ProductList, grpc.ProductList.Builder, grpc.ProductListOrBuilder>(
                listProducts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        listProducts_ = null;
      }
      return listProductsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ProductList)
  }

  // @@protoc_insertion_point(class_scope:ProductList)
  private static final grpc.ProductList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.ProductList();
  }

  public static grpc.ProductList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductList>
      PARSER = new com.google.protobuf.AbstractParser<ProductList>() {
    @java.lang.Override
    public ProductList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProductList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProductList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.ProductList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

