// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package grpc;

public interface ProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Atenção pois o tipo do dado é colocado com letra minúscula no arquivo Proto
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Atenção pois o tipo do dado é colocado com letra minúscula no arquivo Proto
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
