// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package grpc;

public final class ProductProto {
  private ProductProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductRepply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductRepply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveProductReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveProductReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindProductById_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindProductById_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindProducts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindProducts_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeletProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeletProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeletProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeletProductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rProduct.proto\"\036\n\016ProductRequest\022\014\n\004nam" +
      "e\030\001 \001(\t\" \n\rProductRepply\022\017\n\007message\030\001 \001(" +
      "\t\"L\n\022SaveProductRequest\022\n\n\002id\030\001 \001(\003\022\014\n\004n" +
      "ame\030\002 \001(\t\022\r\n\005stock\030\003 \001(\003\022\r\n\005price\030\004 \001(\002\"" +
      "#\n\020SaveProductReply\022\017\n\007message\030\001 \001(\t\"F\n\014" +
      "ProductModel\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\r" +
      "\n\005stock\030\003 \001(\003\022\r\n\005price\030\004 \001(\001\"\035\n\017FindProd" +
      "uctById\022\n\n\002id\030\001 \001(\005\"\016\n\014FindProducts\"1\n\013P" +
      "roductList\022\"\n\014listProducts\030\001 \003(\0132\014.Produ" +
      "ctList\"!\n\023DeletProductRequest\022\n\n\002id\030\001 \001(" +
      "\005\"\'\n\024DeletProductResponse\022\017\n\007message\030\001 \001" +
      "(\t2\227\002\n\007Product\0220\n\013CallProduct\022\017.ProductR" +
      "equest\032\016.ProductRepply\"\000\0227\n\013SaveProduct\022" +
      "\023.SaveProductRequest\032\021.SaveProductReply\"" +
      "\000\0223\n\017ListProductById\022\020.FindProductById\032\014" +
      ".ProductList\"\000\022-\n\014ListProducts\022\r.FindPro" +
      "ducts\032\014.ProductList\"\000\022=\n\014DeletProduct\022\024." +
      "DeletProductRequest\032\025.DeletProductRespon" +
      "se\"\000B\026\n\004grpcB\014ProductProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_ProductRepply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProductRepply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductRepply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_SaveProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SaveProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveProductRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Stock", "Price", });
    internal_static_SaveProductReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SaveProductReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveProductReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_ProductModel_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ProductModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductModel_descriptor,
        new java.lang.String[] { "Id", "Name", "Stock", "Price", });
    internal_static_FindProductById_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_FindProductById_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindProductById_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_FindProducts_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_FindProducts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindProducts_descriptor,
        new java.lang.String[] { });
    internal_static_ProductList_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ProductList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductList_descriptor,
        new java.lang.String[] { "ListProducts", });
    internal_static_DeletProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_DeletProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeletProductRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeletProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_DeletProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeletProductResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
