// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package grpc;

public interface ProductListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ProductList listProducts = 1;</code>
   */
  java.util.List<grpc.ProductList> 
      getListProductsList();
  /**
   * <code>repeated .ProductList listProducts = 1;</code>
   */
  grpc.ProductList getListProducts(int index);
  /**
   * <code>repeated .ProductList listProducts = 1;</code>
   */
  int getListProductsCount();
  /**
   * <code>repeated .ProductList listProducts = 1;</code>
   */
  java.util.List<? extends grpc.ProductListOrBuilder> 
      getListProductsOrBuilderList();
  /**
   * <code>repeated .ProductList listProducts = 1;</code>
   */
  grpc.ProductListOrBuilder getListProductsOrBuilder(
      int index);
}
