// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package grpc;

public interface SaveProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 stock = 3;</code>
   * @return The stock.
   */
  long getStock();

  /**
   * <code>float price = 4;</code>
   * @return The price.
   */
  float getPrice();
}
